### ISSUE TITLE
jcr:mixinTypes shows up as an item - Filter out jcr system properties or arrays

### ISSUE THREAD

**Issue by sameercharles** [namics/aem-generic-multifield#14]
Issue: If the storage node contains a multi value property , it gets picked up by the control and displayed as a list item.
For instance, if you create some content using generic multi field control and do a roll out. The rolled out content will contain jcr:mixinTypes as a multi value property (array when you ask for itemStorageNode json) and we end up with "jcr:mixinTypes" as the first item in the multi field list.
Please see the attached image.
<img width="546" alt="namics" src="https://user-images.githubusercontent.com/8293960/37691245-813510be-2d04-11e8-8134-11e268d167b6.png">

**Comment by suciua** [comment]
Hi @sameercharles 

Could you please attach your dialog.xml or paste the relevant part to this issue? I tried to reproduce it using a multifield within the item dialog but it always worked as expected...

**Comment by suciua** [comment]
Hi @sameercharles 

With the help of my colleagues I managed to reproduce your issue. The issue has been resolved with commit a6faa3e631ace16277517890e00f6be3c997c621 and will be part of the next version (1.0.4).

**Comment by sameercharles** [comment]
Hi @suciua, many thanks for the fix! 
Sorry I was not able to get back on time.
Cheers.
