### ISSUE TITLE
Generic Multifield store itemnode below 

### ISSUE THREAD

**Issue by Walter-Steiner** [namics/aem-generic-multifield#31]
Hi
we just about migrating to aem 6.5 and use the generic multifield. With this version and aem 6.5 it doesn't work anymore.

When I open the dialog in the author (see 2020-03-20 11_56_31-Autoversicherung_ Jetzt Prämie berechnen _ Helvetia.ch.png)
![2020-03-20 11_56_31-Autoversicherung_ Jetzt Prämie berechnen _ Helvetia ch](https://user-images.githubusercontent.com/47733764/77157697-29fe4f80-6aa2-11ea-9d7a-372b8d0978b1.png), no items are displayed. But there should be (see 
![2020-03-20 11_47_50-CRXDE Lite](https://user-images.githubusercontent.com/47733764/77157857-7ba6da00-6aa2-11ea-928a-1b7e75943642.png))

If I add an item in the dialog (see 
![2020-03-20 11_50_15-Autoversicherung_ Jetzt Prämie berechnen _ Helvetia ch](https://user-images.githubusercontent.com/47733764/77157920-99743f00-6aa2-11ea-8554-aa9d9c75b213.png), the item is displayed in the dialog. The node I created is
![2020-03-20 11_51_23-CRXDE Lite](https://user-images.githubusercontent.com/47733764/77158015-c7f21a00-6aa2-11ea-8aa1-0d6f86aac23f.png) locate "/items/3_1584700968848" here.

The dialog looks like:
							<genericmultifield
									jcr:primaryType="nt:unstructured"
									sling:resourceType="namics/genericmultifield"
									fieldLabel="Accordion Item"
									itemDialog="/apps/os/core/component/content/accordion/item-dialog"
									itemStorageNode="items"
									itemNameProperty="title"
									name="./items"/>

The dependency looks like:
			<dependency>
				<groupId>com.namics.oss.aem</groupId>
				<artifactId>genericmultifield</artifactId>
				<version>3.0.0</version>
			</dependency>

Can you please have a look. I didn't change our code. I only upgraded to aem 6.5 and version 3.0.0 of the generic-multifield.

Thanks in advance.

**Comment by Walter-Steiner** [comment]
The dialog seems to have disappeared.
Here it is:
							<genericmultifield
									jcr:primaryType="nt:unstructured"
									sling:resourceType="namics/genericmultifield"
									fieldLabel="Accordion Item"
									itemDialog="/apps/os/core/component/content/accordion/item-dialog"
									itemStorageNode="items"
									itemNameProperty="title"
									name="./items"/>

**Comment by Walter-Steiner** [comment]
Again
							genericmultifield
									jcr:primaryType="nt:unstructured"
									sling:resourceType="namics/genericmultifield"
									fieldLabel="Accordion Item"
									itemDialog="/apps/os/core/component/content/accordion/item-dialog"
									itemStorageNode="items"
									itemNameProperty="title"
									name="./items"

**Comment by sigmaschin** [comment]
Hi,
Sadly for me it works with the following dialog item configuration in AEM 6.5:
![image](https://user-images.githubusercontent.com/6787048/77167047-9171ca80-6ab5-11ea-8e4a-acb066862bf4.png)

Could you maybe check if you have a request like this "http://localhost:4502/content/we-retail/us/en/men/_jcr_content/root/responsivegrid/button_copy/items.-1.json?_=1584710318492" in the network tab of the developer tools? If you have it, it should return the items for the parent dialog.

**Comment by Walter-Steiner** [comment]
Hi
yes I have, but the request looks like "http://localhost:4502/items.-1.json?_=1584719144768". I get a 404 for this request.
Can you give me a hint, how to find the error? Is there a way to debug?
As you can see in my screenshot above, if I add a field with the dialog, the items-node is created under root. I looks like the component looses its context.

**Comment by Walter-Steiner** [comment]
Hi Samuel
I've found the cause, why the items are stored under root-node. In "CUI.GenericMultiField.js" on line 55 crxPath is set.
"55: this.crxPath = this.$element.parents("form").attr("action");"

On my html page, in the form tag the attribute "action" is not set.
<form class="coral-Form--vertical cq-dialog foundation-form foundation-layout-form" **action=""** method="post" data-foundation-form-ajax="true" data-cq-dialog-pageeditor="/editor.html/content/os/ch/web/de/private-customers/vehicles-and-travel/vehicles/car.html">

I also tried with the page "http://localhost:4502/editor.html/content/we-retail/us/en/men.html"
It's not set there either 
<form class="coral-Form--vertical cq-dialog foundation-form foundation-layout-form" **action=""** method="post" data-foundation-form-ajax="true" data-cq-dialog-pageeditor="/editor.html/content/we-retail/us/en/men.html">

I had a look at on the same pages of aem 6.4 sp8. The action is set on the above mentioned pages.

On my aem 6.5 instance I use Service Pack 4.

Did you use aem 6.5 with the same service pack like me?

Thanks for your answer in advance.

Regards
Walter

**Comment by Walter-Steiner** [comment]
Hi Samuel
I've found the cause, why the items are stored under root-node. In "CUI.GenericMultiField.js" on line 55 crxPath is set.
"55: this.crxPath = this.$element.parents("form").attr("action");"

On my html page, in the form tag the attribute "action" is not set.
form class="coral-Form--vertical cq-dialog foundation-form foundation-layout-form" **action=""** method="post" data-foundation-form-ajax="true" data-cq-dialog-pageeditor="/editor.html/content/os/ch/web/de/private-customers/vehicles-and-travel/vehicles/car.html"

I also tried with the page "http://localhost:4502/editor.html/content/we-retail/us/en/men.html"
It's not set there either 
form class="coral-Form--vertical cq-dialog foundation-form foundation-layout-form" **action=""** method="post" data-foundation-form-ajax="true" data-cq-dialog-pageeditor="/editor.html/content/we-retail/us/en/men.html"

I had a look at on the same pages of aem 6.4 sp8. The action is set on the above mentioned pages.

On my aem 6.5 instance I use Service Pack 4.

Did you use aem 6.5 with the same service pack like me?

Thanks for your answer in advance.

Regards
Walter

**Comment by Walter-Steiner** [comment]
Hi Samuel
I setup an author instance 6.5 with Service Pack 3. It works with that service pack. Adobe didn't manage to deliver Service Pack 4 without bugs. Again.
I will close this issue.

**Comment by sigmaschin** [comment]
Hi Walter,
I have checked it locally with AEM 6.5 Service Pack 4 and it works. Could you maybe attach a package with the dialog of the component and the itemDialog of the genericmultifield?

**Comment by sigmaschin** [comment]
I close the issue since we could directly talk to each other and the issue came from another customization (overlay) from the specific project.
